#!/usr/bin/env bash
# Script that displays information about subdomains

get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local full_domain="$subdomain.$domain"
    
    # shellcheck disable=SC2086
    local result
    result=$(dig "$full_domain" +short -t A)
    
    if [ -n "$result" ]; then
        echo "The subdomain $subdomain is a A record and points to $result"
    else
        # Try to get any record type
        # shellcheck disable=SC2086
        dig "$full_domain" | awk -v sub="$subdomain" '
        /ANSWER SECTION:/ {
            getline
            if ($4 == "A" || $4 == "CNAME") {
                printf "The subdomain %s is a %s record and points to %s\n", sub, $4, $5
            }
        }'
    fi
}

# Main script logic
domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    # If no subdomain specified, display info for default subdomains
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
else
    # Display info for the specified subdomain
    get_subdomain_info "$domain" "$subdomain"
fi
